name: Build Resume on PR

on:
  pull_request:
    branches:
      - main

jobs:
  build_resume:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint LaTeX with chktex
        uses: j2kun/chktex-action@v1
        with:
          file: Ayush_Jaipuriyar.tex

      - name: Convert to PDF
        uses: xu-cheng/latex-action@v3
        with:
          root_file: Ayush_Jaipuriyar.tex

      - name: Check PDF exists
        run: |
          if [ ! -f Ayush_Jaipuriyar.pdf ]; then
            echo "PDF not generated"
            exit 1
          fi